### ISSUE TITLE
flutter 支持Windows

### ISSUE THREAD

**Issue by mgt625** [di1shuai/sleep_early#1]
![image](https://user-images.githubusercontent.com/62425993/80327739-b1906880-886f-11ea-867d-04eea5b2bd71.png)
找不到这个window

**Comment by BestBurning** [comment]
desktop层使用的是[go-flutter](https://github.com/go-flutter-desktop/go-flutter#getting-started)
请先参考[go-flutter](https://github.com/go-flutter-desktop/go-flutter#getting-started),配置好`hover`
